language: go

go:
    - 1.3
    - 1.4
    - tip

install:
    - make get-deps
    - go get github.com/axw/gocov/gocov
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls

script:
    - $HOME/gopath/bin/goveralls -service=travis-ci
